format_version: 10
pipelines:
  prometheus:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/saketh-devops-i1/tools.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - APPLY:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            tasks:
            - exec: {command: ansible-playbook, arguments: [ "-i", "prometheus.devops-saketh.online,", "tools.yml", "-e", "tool_name=prometheus", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}